"use client"

import { Check, CreditCard, Download, HardDrive, ReceiptText, RefreshCw, Sparkles } from "lucide-react"
import { Badge, Button, Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle, Progress, Table, TableCell, TableContainer, TableHead, useToast } from "@lexui/react"

export default function BillingPage() {
  const toast = useToast()
  return <><header className="demo-page-header"><div><p className="demo-eyebrow">Assinatura</p><h1>Cobrança</h1><p>Gerencie seu plano, método de pagamento e faturas.</p></div></header>
    <section className="demo-billing-grid"><Card><CardHeader><div className="demo-plan-heading"><div className="demo-card-heading"><span className="demo-entity-icon"><Sparkles size={18} /></span><div><CardDescription>Plano atual</CardDescription><CardTitle>Professional</CardTitle></div></div><Badge variant="primary">Ativo</Badge></div></CardHeader><CardContent><p className="demo-plan-price">R$ 249 <span>/ mês</span></p><ul className="demo-feature-list"><li><Check size={16} />Até 25 membros</li><li><Check size={16} />100 GB de armazenamento</li><li><Check size={16} />Relatórios avançados</li></ul></CardContent><CardFooter><Button variant="outline" onClick={() => toast({ title: "Seletor de planos aberto", description: "Na aplicação real, conecte esta ação ao checkout.", variant: "info" })}><Sparkles size={16} /> Alterar plano</Button></CardFooter></Card>
      <Card><CardHeader><div className="demo-title-with-icon"><CreditCard size={18} /><CardTitle>Método de pagamento</CardTitle></div><CardDescription>Usado na próxima renovação.</CardDescription></CardHeader><CardContent><div className="demo-payment-card"><CreditCard /><div><strong>Visa final 4242</strong><span>Expira em 08/29</span></div><Badge>Principal</Badge></div></CardContent><CardFooter><Button variant="outline" onClick={() => toast({ title: "Atualização de cartão iniciada", variant: "info" })}><RefreshCw size={16} /> Atualizar cartão</Button></CardFooter></Card>
      <Card><CardHeader><div className="demo-title-with-icon"><HardDrive size={18} /><CardTitle>Uso do plano</CardTitle></div><CardDescription>Ciclo de 1 a 31 de julho.</CardDescription></CardHeader><CardContent><div className="demo-setting-list"><Progress label="Membros · 18 de 25" value={72} /><Progress label="Armazenamento · 68 GB de 100 GB" value={68} /></div></CardContent></Card>
    </section>
    <Card><CardHeader><div className="demo-title-with-icon"><ReceiptText size={18} /><CardTitle>Faturas</CardTitle></div><CardDescription>Histórico de pagamentos da organização.</CardDescription></CardHeader><CardContent><TableContainer><Table><thead><tr><TableHead>Fatura</TableHead><TableHead>Data</TableHead><TableHead>Status</TableHead><TableHead>Total</TableHead><TableHead><span className="lex-visually-hidden">Ações</span></TableHead></tr></thead><tbody><Invoice number="INV-2048" date="01 jul 2026" value="R$ 249,00" onDownload={() => toast({ title: "Fatura INV-2048 preparada", variant: "success" })} /><Invoice number="INV-1961" date="01 jun 2026" value="R$ 249,00" onDownload={() => toast({ title: "Fatura INV-1961 preparada", variant: "success" })} /></tbody></Table></TableContainer></CardContent></Card>
  </>
}

function Invoice({ number, date, value, onDownload }: { number: string; date: string; value: string; onDownload: () => void }) { return <tr><TableCell><span className="demo-inline-meta"><ReceiptText size={15} /><strong>{number}</strong></span></TableCell><TableCell>{date}</TableCell><TableCell><Badge variant="success"><Check size={13} />Pago</Badge></TableCell><TableCell>{value}</TableCell><TableCell className="demo-table-actions"><Button variant="ghost" size="sm" onClick={onDownload}><Download size={15} /> Baixar</Button></TableCell></tr> }
