"use client"

import { Alert, Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Checkbox, Progress, Switch, Tabs, TabsContent, TabsList, TabsTrigger, useToast } from "@lexui/react"
import { Bell, HardDrive, Save, Settings2, ShieldCheck, UsersRound } from "lucide-react"

export default function SettingsPage() {
  const toast = useToast()
  return <><header className="demo-page-header"><div><p className="demo-eyebrow">Organização</p><h1>Configurações</h1><p>Controle segurança, notificações e comportamento do workspace.</p></div><Button onClick={() => toast({ title: "Configurações salvas", description: "As preferências foram aplicadas nesta demonstração.", variant: "success" })}><Save size={16} /> Salvar alterações</Button></header>
    <Tabs defaultValue="general"><TabsList><TabsTrigger value="general"><Settings2 size={16} />Geral</TabsTrigger><TabsTrigger value="notifications"><Bell size={16} />Notificações</TabsTrigger><TabsTrigger value="security"><ShieldCheck size={16} />Segurança</TabsTrigger></TabsList>
      <TabsContent value="general"><div className="demo-settings-content"><Card><CardHeader><div className="demo-title-with-icon"><Settings2 size={18} /><CardTitle>Preferências gerais</CardTitle></div><CardDescription>Defina o comportamento padrão para novos membros.</CardDescription></CardHeader><CardContent><div className="demo-setting-list"><Switch label="Tema automático" description="Segue a preferência do sistema operacional." defaultChecked /><Switch label="Modo compacto" description="Reduz espaçamentos em tabelas e dashboards." /><Checkbox label="Permitir convites por membros" description="Administradores continuam com acesso irrestrito." defaultChecked /></div></CardContent></Card><Card><CardHeader><div className="demo-title-with-icon"><HardDrive size={18} /><CardTitle>Uso do workspace</CardTitle></div><CardDescription>Recursos consumidos no ciclo atual.</CardDescription></CardHeader><CardContent><div className="demo-setting-list"><Progress label="Armazenamento" value={68} /><Progress label="Membros" value={42} /></div></CardContent></Card></div></TabsContent>
      <TabsContent value="notifications"><Card><CardHeader><div className="demo-title-with-icon"><Bell size={18} /><CardTitle>Notificações</CardTitle></div><CardDescription>Escolha quais eventos devem gerar avisos.</CardDescription></CardHeader><CardContent><div className="demo-setting-list"><Switch label="Alertas de segurança" description="Login suspeito e alterações de credenciais." defaultChecked /><Switch label="Resumo semanal" description="Indicadores enviados toda segunda-feira." defaultChecked /><Switch label="Atualizações de produto" description="Novidades e melhorias do LexUI." /></div></CardContent></Card></TabsContent>
      <TabsContent value="security"><div className="demo-settings-content"><Alert variant="warning" title="MFA recomendado">Exija autenticação em duas etapas para perfis administrativos.</Alert><Card><CardHeader><div className="demo-title-with-icon"><UsersRound size={18} /><CardTitle>Políticas de acesso</CardTitle></div><CardDescription>Regras aplicadas a toda a organização.</CardDescription></CardHeader><CardContent><div className="demo-setting-list"><Switch label="Exigir MFA de administradores" defaultChecked /><Switch label="Bloquear sessões inativas" description="Encerra sessões após 30 dias sem atividade." defaultChecked /><Checkbox label="Permitir autenticação por SSO" defaultChecked /></div></CardContent></Card></div></TabsContent>
    </Tabs>
  </>
}
