"use client"

import * as React from "react"
import { BarChart3, Bell, Copy, FolderKanban, Grid2X2, LayoutDashboard, List, MessageCircle, MoreHorizontal, Plus, Search, Send, Settings, SlidersHorizontal, Star, Trash2, Users } from "lucide-react"
import { AreaChart, BarChart, DonutChart, HorizontalBarChart, LineChart, PieChart, Sparkline } from "@lexui/charts"
import {
  Accordion, AccordionContent, AccordionItem, AccordionTrigger, Alert, AlertDialog, AlertDialogClose,
  AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogTitle, AlertDialogTrigger,
  Avatar, Badge, Blockquote, Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage,
  BreadcrumbSeparator, Button, Calendar, Card, CardContent, CardDescription, CardFooter, CardHeader, Chat,
  ChatComposer, ChatHeader, ChatMessage, ChatMessages, ChatToolbar,
  CardTitle, Checkbox, Combobox, CommandPalette, ContextMenu, ContextMenuCheckboxItem, ContextMenuContent,
  ContextMenuItem, ContextMenuLabel, ContextMenuSeparator, ContextMenuTrigger, DataTable, DatePicker,
  Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle,
  DialogTrigger, Drawer, DrawerClose, DrawerContent, DrawerDescription, DrawerFooter, DrawerHeader,
  DrawerTitle, DrawerTrigger, DropdownMenu, DropdownMenuCheckboxItem, DropdownMenuContent, DropdownMenuItem,
  DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger, EmptyState, Field, Heading, InlineCode,
  Input, InputOTP, KeyboardKey, Lead, Pagination, Popover, PopoverContent, PopoverDescription, PopoverTitle,
  PopoverTrigger, Progress, RadioGroup, RadioOption, RangeSlider, ScrollArea, Select, Sidebar, SidebarContent,
  SidebarFooter, SidebarGroup, SidebarGroupLabel, SidebarHeader, SidebarItem, SidebarNav, SidebarToggle,
  Skeleton, Slider, Spinner, Switch, Table, TableCell, TableContainer, TableHead, Tabs, TabsContent, TabsList,
  TabsTrigger, Text, Textarea, ThemeToggle, Toggle, ToggleGroup, Tooltip, TooltipProvider, useToast,
} from "@lexui/react"
import {
  AspectRatio, Attachment, Bubble, ButtonGroup, Carousel, CarouselContent, CarouselDots, CarouselItem,
  CarouselNext, CarouselPrevious, Collapsible, CollapsibleContent, CollapsibleTrigger, DirectionProvider,
  HoverCard, HoverCardContent, HoverCardTrigger, InputGroup, InputGroupAddon, Item, ItemActions,
  ItemContent, ItemDescription, ItemMedia, ItemTitle, Label, Marker, Menubar, MenubarContent, MenubarItem,
  MenubarMenu, MenubarShortcut, MenubarTrigger, MessageScroller, NativeSelect, NavigationMenu,
  NavigationMenuContent, NavigationMenuItem, NavigationMenuLink, NavigationMenuList, NavigationMenuTrigger,
  ResizablePanel, ResizablePanelGroup, SelectMenu, Separator, Sheet, SheetClose, SheetContent, SheetDescription,
  SheetFooter, SheetHeader, SheetTitle, SheetTrigger,
} from "@lexui/react"

function ExampleFrame({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) {
  return <section className="demo-example-frame"><div className="demo-example-frame__header"><div><Heading level={2} size="md">{title}</Heading>{description && <Text size="sm" tone="muted">{description}</Text>}</div><Badge variant="success">Ao vivo</Badge></div><div className="demo-example-frame__canvas">{children}</div></section>
}

const roles = [
  { value: "member", label: "Membro", description: "Acesso aos projetos atribuídos" },
  { value: "admin", label: "Administrador", description: "Gerencia pessoas e configurações" },
  { value: "viewer", label: "Visualizador", description: "Acesso somente para leitura" },
]

const tableRows = [
  { id: "1", project: "Portal financeiro", owner: "Ana", status: "Ativo" },
  { id: "2", project: "Onboarding", owner: "Rafael", status: "Ativo" },
  { id: "3", project: "Migração CRM", owner: "Marina", status: "Pausado" },
  { id: "4", project: "Aplicativo mobile", owner: "Caio", status: "Ativo" },
  { id: "5", project: "Novo checkout", owner: "Lia", status: "Revisão" },
  { id: "6", project: "Central de ajuda", owner: "Bia", status: "Ativo" },
]

export function ComponentExample({ slug }: { slug: string }) {
  const toast = useToast()
  const [page, setPage] = React.useState(3)
  const [commandOpen, setCommandOpen] = React.useState(false)
  const [inputValue, setInputValue] = React.useState("")
  const [selectedDate, setSelectedDate] = React.useState<Date | undefined>(new Date())
  const [toggleView, setToggleView] = React.useState<string[]>(["grid"])

  switch (slug) {
    case "typography": return <>
      <ExampleFrame title="Hierarquia"><div className="demo-example-stack demo-example-copy"><Heading level={1} size="2xl">Título principal</Heading><Lead>Texto de abertura que apresenta o contexto da página.</Lead><Heading level={2} size="xl">Título de seção</Heading><Text>Conteúdo principal com leitura confortável e contraste consistente.</Text><Text size="sm" tone="muted">Informação auxiliar com menor ênfase visual.</Text></div></ExampleFrame>
      <ExampleFrame title="Conteúdo técnico"><div className="demo-example-stack demo-example-copy"><Text>Execute <InlineCode>npm run lexui:check</InlineCode> antes de concluir.</Text><Text>Atalho principal: <KeyboardKey>Ctrl K</KeyboardKey></Text><Blockquote>Reutilize componentes públicos antes de criar uma nova abstração.</Blockquote></div></ExampleFrame>
    </>
    case "theme-toggle": return <ExampleFrame title="Tema global" description="Clique para alternar toda a aplicação entre claro e escuro."><div className="demo-example-row"><ThemeToggle /><Text size="sm" tone="muted">A escolha é persistida no navegador.</Text></div></ExampleFrame>
    case "field": return <><ExampleFrame title="Campo completo"><div className="demo-example-form"><Field label="E-mail" htmlFor="field-email" description="Usaremos para notificações importantes."><Input id="field-email" type="email" placeholder="nome@empresa.com" /></Field><Field label="Código" htmlFor="field-error" error="O código informado é inválido."><Input id="field-error" aria-invalid="true" defaultValue="123" /></Field></div></ExampleFrame></>
    case "input": return <ExampleFrame title="Estados"><div className="demo-example-form"><Input placeholder="Digite seu nome" value={inputValue} onChange={(event) => setInputValue(event.target.value)} /><Input type="email" placeholder="nome@empresa.com" /><Input disabled value="Campo desabilitado" /><Text size="sm" tone="muted">Valor digitado: {inputValue || "—"}</Text></div></ExampleFrame>
    case "textarea": return <ExampleFrame title="Texto multilinha"><div className="demo-example-form"><Textarea placeholder="Descreva o objetivo do projeto" defaultValue="Precisamos organizar o fluxo de aprovação e publicação." /><Textarea aria-invalid="true" placeholder="Estado inválido" /></div></ExampleFrame>
    case "select": return <ExampleFrame title="Seleção simples"><div className="demo-example-form"><Select defaultValue="analyst" aria-label="Perfil"><option value="admin">Administrador</option><option value="analyst">Analista</option><option value="viewer">Visualizador</option></Select><Select disabled aria-label="Seleção indisponível"><option>Indisponível</option></Select></div></ExampleFrame>
    case "checkbox": return <ExampleFrame title="Estados de seleção"><div className="demo-example-form"><Checkbox label="Receber novidades" description="No máximo um e-mail por semana." defaultChecked /><Checkbox label="Aceitar os termos" required /><Checkbox label="Seleção parcial" indeterminate /><Checkbox label="Indisponível" disabled /></div></ExampleFrame>
    case "radio-group": return <ExampleFrame title="Escolha exclusiva"><RadioGroup defaultValue="balanced" name="catalog-mode"><RadioOption value="simple" label="Simples" description="Menos opções e decisões rápidas." /><RadioOption value="balanced" label="Equilibrado" description="Recomendado para a maioria dos times." /><RadioOption value="advanced" label="Avançado" description="Controle completo sobre o fluxo." /></RadioGroup></ExampleFrame>
    case "switch": return <ExampleFrame title="Preferências"><div className="demo-example-form"><Switch label="Notificações" description="Avisos importantes da organização." defaultChecked /><Switch label="Relatório semanal" /><Switch label="Indisponível" disabled /></div></ExampleFrame>
    case "slider": return <ExampleFrame title="Valor e intervalo"><div className="demo-example-form"><Slider label="Automação" defaultValue={65} /><RangeSlider label="Faixa de orçamento" defaultValue={[20, 80]} /></div></ExampleFrame>
    case "combobox": return <ExampleFrame title="Busca de opções"><div className="demo-example-narrow"><Combobox options={roles} placeholder="Selecione um perfil" /></div></ExampleFrame>
    case "date-picker": return <ExampleFrame title="Selecionar data"><div className="demo-example-stack"><DatePicker value={selectedDate} onValueChange={setSelectedDate} /><Text size="sm" tone="muted">Data: {selectedDate?.toLocaleDateString("pt-BR")}</Text></div></ExampleFrame>
    case "input-otp": return <ExampleFrame title="Código de verificação"><div className="demo-example-stack"><Text>Digite o código enviado ao dispositivo confiável.</Text><InputOTP length={6} /></div></ExampleFrame>
    case "button": return <><ExampleFrame title="Variantes"><div className="demo-example-row"><Button onClick={() => toast({ title: "Ação executada", variant: "success" })}>Primário</Button><Button variant="accent">Destaque</Button><Button variant="secondary">Secundário</Button><Button variant="outline">Contorno</Button><Button variant="ghost">Ghost</Button><Button variant="destructive">Excluir</Button></div></ExampleFrame><ExampleFrame title="Estados e tamanhos"><div className="demo-example-row"><Button size="sm">Pequeno</Button><Button>Normal</Button><Button loading>Salvando</Button><Button disabled>Desabilitado</Button></div></ExampleFrame></>
    case "toggle": return <ExampleFrame title="Alternador"><div className="demo-example-row"><Toggle defaultPressed><Star size={17} /> Favorito</Toggle><Toggle variant="outline"><Bell size={17} /> Alertas</Toggle></div></ExampleFrame>
    case "toggle-group": return <ExampleFrame title="Visualização"><div className="demo-example-stack"><ToggleGroup value={toggleView} onValueChange={(value) => value.length && setToggleView(value)}><Toggle value="grid" aria-label="Exibir em grade"><Grid2X2 size={17} /></Toggle><Toggle value="list" aria-label="Exibir em lista"><List size={17} /></Toggle></ToggleGroup><Text size="sm" tone="muted">Modo atual: {toggleView[0] === "grid" ? "grade" : "lista"}</Text></div></ExampleFrame>
    case "dropdown-menu": return <ExampleFrame title="Menu de ações"><DropdownMenu><DropdownMenuTrigger render={<Button variant="outline" />}><MoreHorizontal size={17} /> Ações</DropdownMenuTrigger><DropdownMenuContent><DropdownMenuLabel>Registro</DropdownMenuLabel><DropdownMenuItem onClick={() => toast({ title: "Edição aberta" })}>Editar</DropdownMenuItem><DropdownMenuCheckboxItem defaultChecked>Receber alertas</DropdownMenuCheckboxItem><DropdownMenuSeparator /><DropdownMenuItem data-danger onClick={() => toast({ title: "Registro excluído", variant: "danger" })}>Excluir</DropdownMenuItem></DropdownMenuContent></DropdownMenu></ExampleFrame>
    case "context-menu": return <ExampleFrame title="Menu contextual" description="Clique com o botão direito dentro da área tracejada."><ContextMenu><ContextMenuTrigger><div className="demo-context-target"><Heading size="md">Arquivo de referência</Heading><Text size="sm" tone="muted">Em touch, mantenha pressionado.</Text></div></ContextMenuTrigger><ContextMenuContent><ContextMenuLabel>Arquivo</ContextMenuLabel><ContextMenuItem onClick={() => toast({ title: "Arquivo duplicado" })}><Copy size={15} /> Duplicar</ContextMenuItem><ContextMenuCheckboxItem defaultChecked>Disponível offline</ContextMenuCheckboxItem><ContextMenuSeparator /><ContextMenuItem data-danger><Trash2 size={15} /> Excluir</ContextMenuItem></ContextMenuContent></ContextMenu></ExampleFrame>
    case "command-palette": return <ExampleFrame title="Busca por comandos"><><Button onClick={() => setCommandOpen(true)}><Search size={16} /> Abrir comandos</Button><CommandPalette open={commandOpen} onOpenChange={setCommandOpen} groups={[{ label: "Navegação", items: [{ id: "dash", label: "Abrir dashboard", icon: <LayoutDashboard size={17} />, shortcut: "G D", onSelect: () => toast({ title: "Dashboard selecionado" }) }, { id: "projects", label: "Abrir projetos", icon: <FolderKanban size={17} />, shortcut: "G P", onSelect: () => toast({ title: "Projetos selecionado" }) }] }]} /></></ExampleFrame>
    case "alert": return <ExampleFrame title="Variantes semânticas"><div className="demo-example-form"><Alert title="Informação disponível">Confira os detalhes antes de continuar.</Alert><Alert variant="success" title="Alterações salvas">As preferências já estão ativas.</Alert><Alert variant="warning" title="Atenção necessária">Revise os campos destacados.</Alert><Alert variant="danger" title="Não foi possível salvar">Tente novamente em alguns instantes.</Alert></div></ExampleFrame>
    case "badge": return <ExampleFrame title="Status e categorias"><div className="demo-example-row"><Badge>Padrão</Badge><Badge variant="success">Ativo</Badge><Badge variant="warning">Pendente</Badge><Badge variant="danger">Falhou</Badge></div></ExampleFrame>
    case "toast": return <ExampleFrame title="Notificações temporárias"><div className="demo-example-row"><Button onClick={() => toast({ title: "Alterações salvas", description: "As preferências já estão ativas.", variant: "success" })}>Mostrar sucesso</Button><Button variant="accent" onClick={() => toast({ title: "Atenção necessária", description: "Revise os campos destacados.", variant: "warning" })}>Mostrar alerta</Button><Button variant="destructive" onClick={() => toast({ title: "Operação falhou", variant: "danger" })}>Mostrar erro</Button></div></ExampleFrame>
    case "progress": return <ExampleFrame title="Progresso mensurável"><div className="demo-example-form"><Progress label="Armazenamento utilizado" value={68} /><Progress label="Importação de contatos" value={34} /><Progress label="Processamento concluído" value={100} /></div></ExampleFrame>
    case "spinner": return <ExampleFrame title="Espera breve"><div className="demo-example-row"><Spinner /><Button loading>Carregando</Button><Text size="sm" tone="muted">Sincronizando dados…</Text></div></ExampleFrame>
    case "skeleton": return <ExampleFrame title="Estrutura de carregamento"><div className="demo-skeleton-preview"><Skeleton className="demo-skeleton-avatar" /><div><Skeleton className="demo-skeleton-title" /><Skeleton className="demo-skeleton-line" /></div><Skeleton className="demo-skeleton-block" /></div></ExampleFrame>
    case "empty-state": return <ExampleFrame title="Sem resultados"><EmptyState title="Nenhum projeto encontrado" description="Crie o primeiro projeto para começar a acompanhar tarefas e resultados." action={<Button onClick={() => toast({ title: "Novo projeto iniciado", variant: "success" })}><Plus size={16} /> Criar projeto</Button>} /></ExampleFrame>
    case "tooltip": return <ExampleFrame title="Ajuda contextual"><TooltipProvider><div className="demo-example-row"><Tooltip label="Configurações"><Settings size={20} /></Tooltip><Tooltip label="Notificações"><Bell size={20} /></Tooltip><Text size="sm" tone="muted">Passe o mouse ou use o teclado.</Text></div></TooltipProvider></ExampleFrame>
    case "card": return <ExampleFrame title="Composição"><div className="demo-example-grid"><Card><CardHeader><CardTitle>Assinatura</CardTitle><CardDescription>Plano atual da organização.</CardDescription></CardHeader><CardContent><Heading size="lg">Professional</Heading></CardContent><CardFooter><Button size="sm">Gerenciar</Button></CardFooter></Card><Card><CardHeader><CardTitle>Resumo</CardTitle><CardDescription>Indicadores do mês.</CardDescription></CardHeader><CardContent><Text>24 projetos ativos</Text></CardContent></Card></div></ExampleFrame>
    case "tabs": return <ExampleFrame title="Painéis relacionados"><Tabs defaultValue="overview"><TabsList><TabsTrigger value="overview">Visão geral</TabsTrigger><TabsTrigger value="security">Segurança</TabsTrigger><TabsTrigger value="billing">Cobrança</TabsTrigger></TabsList><TabsContent value="overview"><div className="demo-tab-panel">Dados gerais da organização.</div></TabsContent><TabsContent value="security"><div className="demo-tab-panel">Políticas de senha e autenticação.</div></TabsContent><TabsContent value="billing"><div className="demo-tab-panel">Plano, pagamento e faturas.</div></TabsContent></Tabs></ExampleFrame>
    case "accordion": return <ExampleFrame title="Perguntas frequentes"><Accordion defaultValue={["tokens"]}><AccordionItem value="tokens"><AccordionTrigger>Como alterar as cores globais?</AccordionTrigger><AccordionContent>Edite somente os tokens de marca. Os componentes e gráficos herdam as mudanças.</AccordionContent></AccordionItem><AccordionItem value="themes"><AccordionTrigger>O tema escuro é automático?</AccordionTrigger><AccordionContent>O ThemeToggle persiste a preferência e troca os tokens semânticos.</AccordionContent></AccordionItem></Accordion></ExampleFrame>
    case "breadcrumb": return <ExampleFrame title="Hierarquia"><Breadcrumb><BreadcrumbList><BreadcrumbItem><BreadcrumbLink href="/dashboard">Início</BreadcrumbLink></BreadcrumbItem><BreadcrumbSeparator /><BreadcrumbItem><BreadcrumbLink href="/design-system/components">Componentes</BreadcrumbLink></BreadcrumbItem><BreadcrumbSeparator /><BreadcrumbItem><BreadcrumbPage>Breadcrumb</BreadcrumbPage></BreadcrumbItem></BreadcrumbList></Breadcrumb></ExampleFrame>
    case "pagination": return <ExampleFrame title="Navegação de páginas"><div className="demo-example-stack"><Text>Página atual: {page}</Text><Pagination page={page} totalPages={8} onPageChange={setPage} /></div></ExampleFrame>
    case "sidebar": return <ExampleFrame title="Navegação recolhível"><div className="demo-sidebar-preview"><Sidebar><SidebarHeader><strong>LexUI</strong><SidebarToggle /></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>Workspace</SidebarGroupLabel><SidebarNav aria-label="Exemplo"><SidebarItem href="#component-preview" icon={<BarChart3 size={18} />} active>Dashboard</SidebarItem><SidebarItem href="#component-preview" icon={<FolderKanban size={18} />}>Projetos</SidebarItem><SidebarItem href="#component-preview" icon={<Users size={18} />} badge={<Badge>12</Badge>}>Time</SidebarItem></SidebarNav></SidebarGroup></SidebarContent><SidebarFooter>Conta LexUI</SidebarFooter></Sidebar><div className="demo-sidebar-preview__content">Conteúdo da aplicação</div></div></ExampleFrame>
    case "scroll-area": return <ExampleFrame title="Conteúdo com rolagem"><ScrollArea className="demo-scroll-preview"><div className="demo-scroll-preview__content">{Array.from({ length: 18 }, (_, index) => <div key={index}><strong>Atividade {index + 1}</strong><Text size="sm" tone="muted">Registro preservado na área de rolagem.</Text></div>)}</div></ScrollArea></ExampleFrame>
    case "table": return <ExampleFrame title="Tabela semântica"><TableContainer><Table><thead><tr><TableHead>Nome</TableHead><TableHead>Perfil</TableHead><TableHead>Status</TableHead></tr></thead><tbody><tr><TableCell>Ana Lima</TableCell><TableCell>Admin</TableCell><TableCell><Badge variant="success">Ativa</Badge></TableCell></tr><tr><TableCell>Rafael Costa</TableCell><TableCell>Analista</TableCell><TableCell><Badge variant="warning">Convite</Badge></TableCell></tr></tbody></Table></TableContainer></ExampleFrame>
    case "data-table": return <ExampleFrame title="Busca, ordenação e paginação"><DataTable data={tableRows} rowId={(row) => row.id} pageSize={4} searchText={(row) => `${row.project} ${row.owner} ${row.status}`} columns={[{ id: "project", header: "Projeto", accessor: "project", sortable: true }, { id: "owner", header: "Responsável", accessor: "owner", sortable: true }, { id: "status", header: "Status", accessor: "status", sortable: true, cell: (row) => <Badge variant={row.status === "Ativo" ? "success" : "warning"}>{row.status}</Badge> }]} actions={<Button onClick={() => toast({ title: "Novo projeto" })}><Plus size={16} /> Novo</Button>} /></ExampleFrame>
    case "calendar": return <ExampleFrame title="Calendário mensal"><div className="demo-example-stack"><Calendar value={selectedDate} onValueChange={setSelectedDate} /><Text size="sm" tone="muted">Selecionada: {selectedDate?.toLocaleDateString("pt-BR")}</Text></div></ExampleFrame>
    case "bar-chart": return <><ExampleFrame title="Série categórica"><BarChart label="Receita mensal" data={[{ label: "Jan", value: 42 }, { label: "Fev", value: 58 }, { label: "Mar", value: 51 }, { label: "Abr", value: 76 }, { label: "Mai", value: 91 }]} valueFormatter={(value) => `R$ ${value}k`} /></ExampleFrame><ExampleFrame title="Tom contextual"><BarChart label="Conversão" tone="positive" data={[{ label: "Seg", value: 32 }, { label: "Ter", value: 47 }, { label: "Qua", value: 39 }, { label: "Qui", value: 61 }]} valueFormatter={(value) => `${value}%`} /></ExampleFrame></>
    case "horizontal-bar-chart": return <ExampleFrame title="Ranking por canal"><HorizontalBarChart label="Aquisição por canal" data={[{ label: "Orgânico", value: 84 }, { label: "Indicação", value: 67 }, { label: "Mídia", value: 52 }, { label: "Eventos", value: 31 }]} valueFormatter={(value) => `${value}%`} /></ExampleFrame>
    case "line-chart": return <><ExampleFrame title="Evolução de receita"><LineChart label="Receita nos últimos seis meses" data={[{ label: "Jan", value: 42 }, { label: "Fev", value: 58 }, { label: "Mar", value: 51 }, { label: "Abr", value: 76 }, { label: "Mai", value: 91 }, { label: "Jun", value: 88 }]} valueFormatter={(value) => `R$ ${value}k`} /></ExampleFrame><ExampleFrame title="Tendência positiva"><LineChart label="Usuários ativos" tone="positive" data={[{ label: "Seg", value: 22 }, { label: "Ter", value: 35 }, { label: "Qua", value: 31 }, { label: "Qui", value: 48 }, { label: "Sex", value: 63 }]} /></ExampleFrame></>
    case "area-chart": return <ExampleFrame title="Volume acumulado"><AreaChart label="Volume de mensagens" data={[{ label: "Jan", value: 28 }, { label: "Fev", value: 44 }, { label: "Mar", value: 39 }, { label: "Abr", value: 62 }, { label: "Mai", value: 79 }, { label: "Jun", value: 96 }]} valueFormatter={(value) => `${value} mil`} /></ExampleFrame>
    case "pie-chart": return <ExampleFrame title="Distribuição por plano"><PieChart label="Clientes por plano" data={[{ label: "Starter", value: 34 }, { label: "Professional", value: 46 }, { label: "Business", value: 20 }]} valueFormatter={(value) => `${value}%`} /></ExampleFrame>
    case "donut-chart": return <ExampleFrame title="Tickets por status"><DonutChart label="Tickets por status" centerValue="248" centerLabel="Tickets" data={[{ label: "Resolvidos", value: 148 }, { label: "Em andamento", value: 62 }, { label: "Aguardando", value: 38 }]} /></ExampleFrame>
    case "sparkline": return <ExampleFrame title="Métricas compactas"><div className="demo-sparkline-grid"><Card><CardHeader><CardDescription>Receita</CardDescription><CardTitle>R$ 184 mil</CardTitle></CardHeader><CardContent><Sparkline label="Tendência de receita" data={[{ label: "1", value: 22 }, { label: "2", value: 31 }, { label: "3", value: 28 }, { label: "4", value: 44 }, { label: "5", value: 51 }]} /></CardContent></Card><Card><CardHeader><CardDescription>Cancelamentos</CardDescription><CardTitle>1,8%</CardTitle></CardHeader><CardContent><Sparkline label="Tendência de cancelamentos" tone="negative" data={[{ label: "1", value: 5 }, { label: "2", value: 4 }, { label: "3", value: 6 }, { label: "4", value: 3 }, { label: "5", value: 2 }]} /></CardContent></Card></div></ExampleFrame>
    case "avatar": return <ExampleFrame title="Tamanhos e fallback"><div className="demo-example-row"><Avatar name="Ana Lima" size="sm" /><Avatar name="Rafael Costa" /><Avatar name="Marina Souza" size="lg" /><Text size="sm" tone="muted">Iniciais são geradas automaticamente.</Text></div></ExampleFrame>
    case "dialog": return <ExampleFrame title="Modal de tarefa"><Dialog><DialogTrigger render={<Button />}>Convidar pessoa</DialogTrigger><DialogContent><DialogHeader><DialogTitle>Convidar pessoa</DialogTitle><DialogDescription>Envie um convite para participar da organização.</DialogDescription></DialogHeader><div className="demo-example-form demo-dialog-form"><Field label="E-mail" htmlFor="dialog-email"><Input id="dialog-email" type="email" placeholder="nome@empresa.com" /></Field></div><DialogFooter><DialogClose render={<Button variant="ghost" />}>Cancelar</DialogClose><DialogClose render={<Button />}>Enviar convite</DialogClose></DialogFooter></DialogContent></Dialog></ExampleFrame>
    case "alert-dialog": return <ExampleFrame title="Confirmação crítica"><AlertDialog><AlertDialogTrigger render={<Button variant="destructive" />}>Excluir projeto</AlertDialogTrigger><AlertDialogContent><AlertDialogTitle>Excluir este projeto?</AlertDialogTitle><AlertDialogDescription>Esta ação é permanente e removerá os dados associados.</AlertDialogDescription><AlertDialogFooter><AlertDialogClose render={<Button variant="outline" />}>Cancelar</AlertDialogClose><AlertDialogClose render={<Button variant="destructive" />}>Excluir</AlertDialogClose></AlertDialogFooter></AlertDialogContent></AlertDialog></ExampleFrame>
    case "drawer": return <ExampleFrame title="Painel lateral"><Drawer><DrawerTrigger render={<Button />}>Novo evento</DrawerTrigger><DrawerContent><DrawerHeader><DrawerTitle>Criar evento</DrawerTitle><DrawerDescription>Preencha os dados essenciais e confirme.</DrawerDescription></DrawerHeader><div className="demo-example-form demo-drawer-form"><Field label="Título" htmlFor="drawer-title"><Input id="drawer-title" placeholder="Reunião de planejamento" /></Field><Field label="Data" htmlFor="drawer-date"><Input id="drawer-date" type="date" /></Field></div><DrawerFooter><DrawerClose render={<Button variant="outline" />}>Cancelar</DrawerClose><DrawerClose render={<Button />}>Criar evento</DrawerClose></DrawerFooter></DrawerContent></Drawer></ExampleFrame>
    case "popover": return <ExampleFrame title="Conteúdo ancorado"><Popover><PopoverTrigger render={<Button variant="secondary" />}><SlidersHorizontal size={17} /> Filtros</PopoverTrigger><PopoverContent><PopoverTitle>Filtros rápidos</PopoverTitle><PopoverDescription>Refine a lista sem perder o contexto atual.</PopoverDescription><div className="demo-example-form demo-popover-form"><Checkbox label="Somente ativos" defaultChecked /><Checkbox label="Meus projetos" /></div></PopoverContent></Popover></ExampleFrame>
    case "chat": return <ExampleFrame title="Conversa básica"><div className="demo-example-narrow"><Chat><ChatHeader><strong>Assistente Lex</strong><Badge variant="success">Online</Badge></ChatHeader><ChatMessages><ChatMessage author="Assistente" avatar={<Avatar name="Lex IA" size="sm" />}>Olá! Posso analisar seus dados e documentos.</ChatMessage><ChatMessage role="user" author="Você">Mostre o resumo da semana.</ChatMessage></ChatMessages><ChatComposer onSubmit={(event) => event.preventDefault()}><Textarea rows={2} placeholder="Digite uma mensagem…" aria-label="Mensagem" /><ChatToolbar><Button size="sm"><Send size={15} /> Enviar</Button><a className="demo-inline-link" href="/chat"><MessageCircle size={15} /> Ver exemplo completo</a></ChatToolbar></ChatComposer></Chat></div></ExampleFrame>
    case "aspect-ratio": return <ExampleFrame title="Mídia responsiva"><div className="demo-example-narrow"><AspectRatio ratio={16 / 9} className="demo-aspect-preview"><div><BarChart3 size={36} /><strong>Preview 16:9</strong></div></AspectRatio></div></ExampleFrame>
    case "attachment": return <ExampleFrame title="Arquivos anexados"><div className="demo-example-form"><Attachment name="relatorio-trimestral.pdf" metadata="PDF · 2,4 MB" onRemove={() => toast({ title: "Anexo removido" })} /><Attachment name="base-clientes.csv" metadata="CSV · 840 KB" /></div></ExampleFrame>
    case "bubble": return <ExampleFrame title="Papéis de conversa"><div className="demo-example-form"><Bubble>Posso ajudar a analisar os indicadores.</Bubble><Bubble role="user">Compare os dois últimos meses.</Bubble><Bubble role="system">Fonte comercial conectada.</Bubble></div></ExampleFrame>
    case "button-group": return <ExampleFrame title="Ações relacionadas"><ButtonGroup><Button variant="outline"><Grid2X2 size={16} /> Grade</Button><Button variant="outline"><List size={16} /> Lista</Button><Button variant="outline" size="icon" aria-label="Mais opções"><MoreHorizontal size={16} /></Button></ButtonGroup></ExampleFrame>
    case "carousel": return <ExampleFrame title="Destaques navegáveis"><Carousel><CarouselContent>{["Receita cresceu 18%", "42 novos clientes", "Churn caiu para 1,8%"].map((text, index) => <CarouselItem key={text}><Card><CardHeader><CardDescription>Destaque {index + 1}</CardDescription><CardTitle>{text}</CardTitle></CardHeader></Card></CarouselItem>)}</CarouselContent><CarouselPrevious /><CarouselNext /><CarouselDots /></Carousel></ExampleFrame>
    case "collapsible": return <ExampleFrame title="Detalhes sob demanda"><Collapsible><CollapsibleTrigger>Ver fontes e metodologia</CollapsibleTrigger><CollapsibleContent><Text size="sm">Dados consolidados da base comercial e meta trimestral.</Text></CollapsibleContent></Collapsible></ExampleFrame>
    case "direction": return <ExampleFrame title="Direção do conteúdo"><div className="demo-example-grid"><DirectionProvider dir="ltr"><Card><CardContent>Interface LTR →</CardContent></Card></DirectionProvider><DirectionProvider dir="rtl"><Card><CardContent>واجهة RTL ←</CardContent></Card></DirectionProvider></div></ExampleFrame>
    case "hover-card": return <ExampleFrame title="Preview por hover ou foco"><Text>Responsável: <HoverCard><HoverCardTrigger>Ana Lima</HoverCardTrigger><HoverCardContent><Avatar name="Ana Lima" /><strong>Ana Lima</strong><Text as="span" size="sm" tone="muted">Product Designer · Online</Text></HoverCardContent></HoverCard></Text></ExampleFrame>
    case "input-group": return <ExampleFrame title="Prefixos e ações"><div className="demo-example-form"><InputGroup><InputGroupAddon>https://</InputGroupAddon><Input defaultValue="lexui.dev" aria-label="Domínio" /><InputGroupAddon align="end">.com</InputGroupAddon></InputGroup><InputGroup><Input placeholder="Buscar projeto" aria-label="Busca" /><Button size="icon" aria-label="Buscar"><Search size={16} /></Button></InputGroup></div></ExampleFrame>
    case "item": return <ExampleFrame title="Lista composta"><div className="demo-example-form">{["Portal financeiro", "Central de conhecimento"].map((name) => <Item variant="outline" key={name}><ItemMedia><FolderKanban size={20} /></ItemMedia><ItemContent><ItemTitle>{name}</ItemTitle><ItemDescription>Atualizado hoje por Ana Lima</ItemDescription></ItemContent><ItemActions><Button size="icon" variant="ghost" aria-label={`Abrir ações de ${name}`}><MoreHorizontal size={17} /></Button></ItemActions></Item>)}</div></ExampleFrame>
    case "label": return <ExampleFrame title="Rótulo explícito"><div className="demo-example-form"><Label htmlFor="label-example">Nome da organização</Label><Input id="label-example" placeholder="LexUI Labs" /></div></ExampleFrame>
    case "marker": return <ExampleFrame title="Estados compactos"><div className="demo-example-row"><Marker tone="positive" pulse>Online</Marker><Marker tone="warning">Aguardando</Marker><Marker tone="negative">Falhou</Marker><Marker tone="primary">Em revisão</Marker></div></ExampleFrame>
    case "menubar": return <ExampleFrame title="Comandos da aplicação"><Menubar><MenubarMenu><MenubarTrigger>Arquivo</MenubarTrigger><MenubarContent><MenubarItem>Novo projeto<MenubarShortcut>Ctrl N</MenubarShortcut></MenubarItem><MenubarItem>Exportar<MenubarShortcut>Ctrl E</MenubarShortcut></MenubarItem></MenubarContent></MenubarMenu><MenubarMenu><MenubarTrigger>Editar</MenubarTrigger><MenubarContent><MenubarItem>Desfazer<MenubarShortcut>Ctrl Z</MenubarShortcut></MenubarItem></MenubarContent></MenubarMenu></Menubar></ExampleFrame>
    case "message-scroller": return <ExampleFrame title="Fluxo rolável"><MessageScroller>{Array.from({ length: 8 }, (_, index) => <Bubble role={index % 2 ? "user" : "assistant"} key={index}>Mensagem de exemplo {index + 1}</Bubble>)}</MessageScroller></ExampleFrame>
    case "native-select": return <ExampleFrame title="Seleção nativa"><NativeSelect defaultValue="br" aria-label="País"><option value="br">Brasil</option><option value="pt">Portugal</option><option value="ao">Angola</option></NativeSelect></ExampleFrame>
    case "navigation-menu": return <ExampleFrame title="Navegação rica"><NavigationMenu aria-label="Produto"><NavigationMenuList><NavigationMenuItem><NavigationMenuLink href="#component-preview" active>Visão geral</NavigationMenuLink></NavigationMenuItem><NavigationMenuItem><NavigationMenuTrigger>Recursos</NavigationMenuTrigger><NavigationMenuContent><Item><ItemMedia><BarChart3 size={18} /></ItemMedia><ItemContent><ItemTitle>Analytics</ItemTitle><ItemDescription>Indicadores e relatórios interativos</ItemDescription></ItemContent></Item></NavigationMenuContent></NavigationMenuItem><NavigationMenuItem><NavigationMenuLink href="#component-preview">Preços</NavigationMenuLink></NavigationMenuItem></NavigationMenuList></NavigationMenu></ExampleFrame>
    case "resizable": return <ExampleFrame title="Painéis ajustáveis"><ResizablePanelGroup><ResizablePanel><Heading size="md">Navegação</Heading><Text size="sm" tone="muted">Arraste o divisor ou use as setas.</Text></ResizablePanel><ResizablePanel><Heading size="md">Conteúdo</Heading><Text>Área principal redimensionável.</Text></ResizablePanel></ResizablePanelGroup></ExampleFrame>
    case "select-menu": return <ExampleFrame title="Seleção composta"><SelectMenu label="Selecionar agente" placeholder="Escolha um agente" defaultValue="analyst" options={[{ value: "analyst", label: "Analista de dados" }, { value: "support", label: "Especialista de suporte" }, { value: "writer", label: "Redator" }]} /></ExampleFrame>
    case "separator": return <ExampleFrame title="Divisores"><div className="demo-example-stack"><Text>Conteúdo acima</Text><Separator /><div className="demo-example-row"><Text>Esquerda</Text><Separator orientation="vertical" /><Text>Direita</Text></div></div></ExampleFrame>
    case "sheet": return <ExampleFrame title="Painel modal lateral"><Sheet><SheetTrigger render={<Button />}>Abrir detalhes</SheetTrigger><SheetContent><SheetHeader><SheetTitle>Detalhes do projeto</SheetTitle><SheetDescription>Revise informações sem sair da página.</SheetDescription></SheetHeader><div className="demo-example-form demo-drawer-form"><Field label="Nome" htmlFor="sheet-project"><Input id="sheet-project" defaultValue="Portal financeiro" /></Field></div><SheetFooter><SheetClose render={<Button />}>Concluir</SheetClose></SheetFooter></SheetContent></Sheet></ExampleFrame>
    default: return <Alert variant="warning" title="Exemplo indisponível">Este componente ainda não possui demonstração registrada.</Alert>
  }
}
