// Gerado por `pnpm icons:reference` (scripts/collect-icons.mjs). Não editar manualmente.
// Reúne os ícones lucide-react importados no repositório e o vocabulário aprovado em
// .design-system-lex-ui/foundations/icon-vocabulary.json (uses 0 = aprovado, ainda sem uso).
import type { LucideIcon } from "lucide-react"
import {
  AlignCenter,
  AlignLeft,
  AlignRight,
  AppWindow,
  Archive,
  ArrowDown,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  ArrowUpRight,
  BadgeCheck,
  Banknote,
  BarChart3,
  Bell,
  BellRing,
  Blocks,
  BookOpen,
  Bot,
  BriefcaseBusiness,
  Building2,
  CalendarClock,
  CalendarDays,
  CalendarPlus,
  ChartNoAxesCombined,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleDollarSign,
  CirclePause,
  ClipboardList,
  Clock3,
  Component,
  Copy,
  CreditCard,
  Database,
  Download,
  ExternalLink,
  File,
  FileChartColumn,
  FilePenLine,
  FileText,
  FingerprintPattern,
  FolderKanban,
  FolderLock,
  FormInput,
  Gavel,
  Grid2X2,
  GripVertical,
  Handshake,
  HardDrive,
  Hourglass,
  IdCard,
  Inbox,
  Info,
  KeyRound,
  Landmark,
  Layers,
  LayoutDashboard,
  LayoutPanelTop,
  Library,
  List,
  ListFilter,
  LoaderCircle,
  LockKeyhole,
  LogIn,
  Mail,
  Maximize2,
  Menu,
  MessageCircle,
  Mic,
  Minus,
  Moon,
  MoreHorizontal,
  MousePointerClick,
  NotebookPen,
  PanelLeftClose,
  PanelLeftOpen,
  Paperclip,
  Plug,
  Plus,
  ReceiptText,
  RefreshCcw,
  RefreshCw,
  RotateCcw,
  Save,
  Scale,
  ScrollText,
  Search,
  Send,
  Settings,
  Settings2,
  ShieldCheck,
  ShieldUser,
  ShoppingCart,
  Signature,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Stamp,
  Star,
  Sun,
  Trash2,
  TriangleAlert,
  Upload,
  UploadCloud,
  UserCheck,
  UserPlus,
  UserRound,
  Users,
  UsersRound,
  X,
  XCircle,
} from "lucide-react"
export const iconsReference: { icon: LucideIcon; name: string; uses: number; concept?: string; use?: string }[] = [
  { icon: AlignCenter, name: "AlignCenter", uses: 1 },
  { icon: AlignLeft, name: "AlignLeft", uses: 1 },
  { icon: AlignRight, name: "AlignRight", uses: 1 },
  { icon: AppWindow, name: "AppWindow", uses: 1 },
  { icon: Archive, name: "Archive", uses: 0, concept: "Arquivamento", use: "Processos e documentos arquivados ou encerrados." },
  { icon: ArrowDown, name: "ArrowDown", uses: 1 },
  { icon: ArrowDownRight, name: "ArrowDownRight", uses: 1 },
  { icon: ArrowLeft, name: "ArrowLeft", uses: 1 },
  { icon: ArrowRight, name: "ArrowRight", uses: 2 },
  { icon: ArrowUp, name: "ArrowUp", uses: 1 },
  { icon: ArrowUpDown, name: "ArrowUpDown", uses: 1 },
  { icon: ArrowUpRight, name: "ArrowUpRight", uses: 1 },
  { icon: BadgeCheck, name: "BadgeCheck", uses: 0, concept: "Certidão válida", use: "Certidões, documentos válidos e verificação concluída." },
  { icon: Banknote, name: "Banknote", uses: 0, concept: "Honorários e custas", use: "Honorários, custas e depósitos judiciais." },
  { icon: BarChart3, name: "BarChart3", uses: 6 },
  { icon: Bell, name: "Bell", uses: 5 },
  { icon: BellRing, name: "BellRing", uses: 1 },
  { icon: Blocks, name: "Blocks", uses: 3 },
  { icon: BookOpen, name: "BookOpen", uses: 1 },
  { icon: Bot, name: "Bot", uses: 1 },
  { icon: BriefcaseBusiness, name: "BriefcaseBusiness", uses: 0, concept: "Carteira de casos", use: "Carteira, área de atuação e visão do escritório." },
  { icon: Building2, name: "Building2", uses: 1 },
  { icon: CalendarClock, name: "CalendarClock", uses: 0, concept: "Prazo datado", use: "Prazos com data e hora, intimações e compromissos agendados." },
  { icon: CalendarDays, name: "CalendarDays", uses: 2 },
  { icon: CalendarPlus, name: "CalendarPlus", uses: 1 },
  { icon: ChartNoAxesCombined, name: "ChartNoAxesCombined", uses: 1 },
  { icon: Check, name: "Check", uses: 6 },
  { icon: CheckCheck, name: "CheckCheck", uses: 1 },
  { icon: ChevronDown, name: "ChevronDown", uses: 5 },
  { icon: ChevronLeft, name: "ChevronLeft", uses: 3 },
  { icon: ChevronRight, name: "ChevronRight", uses: 4 },
  { icon: CircleAlert, name: "CircleAlert", uses: 2 },
  { icon: CircleCheck, name: "CircleCheck", uses: 8 },
  { icon: CircleDollarSign, name: "CircleDollarSign", uses: 1 },
  { icon: CirclePause, name: "CirclePause", uses: 1 },
  { icon: ClipboardList, name: "ClipboardList", uses: 0, concept: "Andamento processual", use: "Checklist de atos, andamentos e movimentações." },
  { icon: Clock3, name: "Clock3", uses: 2 },
  { icon: Component, name: "Component", uses: 1 },
  { icon: Copy, name: "Copy", uses: 3 },
  { icon: CreditCard, name: "CreditCard", uses: 2 },
  { icon: Database, name: "Database", uses: 1 },
  { icon: Download, name: "Download", uses: 5 },
  { icon: ExternalLink, name: "ExternalLink", uses: 3 },
  { icon: File, name: "File", uses: 1 },
  { icon: FileChartColumn, name: "FileChartColumn", uses: 1 },
  { icon: FilePenLine, name: "FilePenLine", uses: 0, concept: "Peça em elaboração", use: "Minutas, petições em redação e procurações ainda não protocoladas." },
  { icon: FileText, name: "FileText", uses: 2 },
  { icon: FingerprintPattern, name: "FingerprintPattern", uses: 0, concept: "Assinatura digital", use: "Autenticação e assinatura eletrônica com validade jurídica." },
  { icon: FolderKanban, name: "FolderKanban", uses: 7 },
  { icon: FolderLock, name: "FolderLock", uses: 0, concept: "Autos sigilosos", use: "Pastas e autos com acesso restrito." },
  { icon: FormInput, name: "FormInput", uses: 1 },
  { icon: Gavel, name: "Gavel", uses: 1, concept: "Audiência e decisão", use: "Audiências, despachos, sentenças e atos decisórios." },
  { icon: Grid2X2, name: "Grid2X2", uses: 3 },
  { icon: GripVertical, name: "GripVertical", uses: 1 },
  { icon: Handshake, name: "Handshake", uses: 1, concept: "Acordo e conciliação", use: "Acordos, conciliações e negociações encerradas." },
  { icon: HardDrive, name: "HardDrive", uses: 2 },
  { icon: Hourglass, name: "Hourglass", uses: 1, concept: "Decurso de prazo", use: "Contagem de prazo em andamento." },
  { icon: IdCard, name: "IdCard", uses: 0, concept: "Cadastro de parte", use: "Ficha cadastral, identificação e habilitação." },
  { icon: Inbox, name: "Inbox", uses: 1 },
  { icon: Info, name: "Info", uses: 2 },
  { icon: KeyRound, name: "KeyRound", uses: 1 },
  { icon: Landmark, name: "Landmark", uses: 1, concept: "Tribunal e órgão público", use: "Varas, tribunais e órgãos públicos." },
  { icon: Layers, name: "Layers", uses: 1 },
  { icon: LayoutDashboard, name: "LayoutDashboard", uses: 2 },
  { icon: LayoutPanelTop, name: "LayoutPanelTop", uses: 1 },
  { icon: Library, name: "Library", uses: 0, concept: "Acervo jurídico", use: "Biblioteca de peças, modelos e jurisprudência." },
  { icon: List, name: "List", uses: 3 },
  { icon: ListFilter, name: "ListFilter", uses: 1 },
  { icon: LoaderCircle, name: "LoaderCircle", uses: 2 },
  { icon: LockKeyhole, name: "LockKeyhole", uses: 0, concept: "Segredo de justiça", use: "Restrição de acesso e sigilo processual." },
  { icon: LogIn, name: "LogIn", uses: 1 },
  { icon: Mail, name: "Mail", uses: 1 },
  { icon: Maximize2, name: "Maximize2", uses: 1 },
  { icon: Menu, name: "Menu", uses: 2 },
  { icon: MessageCircle, name: "MessageCircle", uses: 3 },
  { icon: Mic, name: "Mic", uses: 1 },
  { icon: Minus, name: "Minus", uses: 1 },
  { icon: Moon, name: "Moon", uses: 1 },
  { icon: MoreHorizontal, name: "MoreHorizontal", uses: 4 },
  { icon: MousePointerClick, name: "MousePointerClick", uses: 2 },
  { icon: NotebookPen, name: "NotebookPen", uses: 0, concept: "Ata e anotação", use: "Atas de audiência e anotações de atendimento." },
  { icon: PanelLeftClose, name: "PanelLeftClose", uses: 1 },
  { icon: PanelLeftOpen, name: "PanelLeftOpen", uses: 1 },
  { icon: Paperclip, name: "Paperclip", uses: 2 },
  { icon: Plug, name: "Plug", uses: 1 },
  { icon: Plus, name: "Plus", uses: 4 },
  { icon: ReceiptText, name: "ReceiptText", uses: 1 },
  { icon: RefreshCcw, name: "RefreshCcw", uses: 1 },
  { icon: RefreshCw, name: "RefreshCw", uses: 1 },
  { icon: RotateCcw, name: "RotateCcw", uses: 1 },
  { icon: Save, name: "Save", uses: 2 },
  { icon: Scale, name: "Scale", uses: 0, concept: "Processo e justiça", use: "Visão de processo, jurimetria e indicadores de decisão." },
  { icon: ScrollText, name: "ScrollText", uses: 0, concept: "Lei e norma", use: "Legislação, súmulas e normativos citados na peça." },
  { icon: Search, name: "Search", uses: 9 },
  { icon: Send, name: "Send", uses: 3 },
  { icon: Settings, name: "Settings", uses: 4 },
  { icon: Settings2, name: "Settings2", uses: 2 },
  { icon: ShieldCheck, name: "ShieldCheck", uses: 5 },
  { icon: ShieldUser, name: "ShieldUser", uses: 0, concept: "Representação e sigilo", use: "Atuação sob procuração e proteção dos dados da parte." },
  { icon: ShoppingCart, name: "ShoppingCart", uses: 1 },
  { icon: Signature, name: "Signature", uses: 0, concept: "Assinatura e aceite", use: "Campos e fluxos de assinatura, aceite e documento já assinado." },
  { icon: SlidersHorizontal, name: "SlidersHorizontal", uses: 3 },
  { icon: Smartphone, name: "Smartphone", uses: 1 },
  { icon: Sparkles, name: "Sparkles", uses: 2 },
  { icon: Stamp, name: "Stamp", uses: 0, concept: "Protocolo e autenticação", use: "Protocolo, carimbo e autenticação de cópia." },
  { icon: Star, name: "Star", uses: 2 },
  { icon: Sun, name: "Sun", uses: 1 },
  { icon: Trash2, name: "Trash2", uses: 6 },
  { icon: TriangleAlert, name: "TriangleAlert", uses: 3 },
  { icon: Upload, name: "Upload", uses: 1 },
  { icon: UploadCloud, name: "UploadCloud", uses: 1 },
  { icon: UserCheck, name: "UserCheck", uses: 0, concept: "Parte qualificada", use: "Cliente ou parte com cadastro e qualificação confirmados." },
  { icon: UserPlus, name: "UserPlus", uses: 1 },
  { icon: UserRound, name: "UserRound", uses: 4 },
  { icon: Users, name: "Users", uses: 2 },
  { icon: UsersRound, name: "UsersRound", uses: 3 },
  { icon: X, name: "X", uses: 10 },
  { icon: XCircle, name: "XCircle", uses: 2 },
]
