// Gerado por `pnpm icons:reference` (scripts/collect-icons.mjs). Não editar manualmente.
// A referência deve refletir os ícones lucide-react importados no repositório.
import type { LucideIcon } from "lucide-react"
import {
  AlertTriangle,
  AlignCenter,
  AlignLeft,
  AlignRight,
  AppWindow,
  ArrowDown,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  ArrowUpRight,
  BarChart3,
  Bell,
  BellRing,
  Blocks,
  BookOpen,
  Bot,
  Building2,
  CalendarDays,
  CalendarPlus,
  ChartNoAxesCombined,
  Check,
  CheckCheck,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleDollarSign,
  CirclePause,
  Clock3,
  Component,
  Copy,
  CreditCard,
  Database,
  Download,
  ExternalLink,
  File,
  FileChartColumn,
  FileText,
  FolderKanban,
  FormInput,
  Grid2X2,
  GripVertical,
  HardDrive,
  Inbox,
  Info,
  KeyRound,
  Landmark,
  Layers,
  LayoutDashboard,
  LayoutPanelTop,
  List,
  ListFilter,
  LoaderCircle,
  LogIn,
  Mail,
  Maximize2,
  Menu,
  MessageCircle,
  Mic,
  Minus,
  Moon,
  MoreHorizontal,
  MousePointerClick,
  PanelLeftClose,
  PanelLeftOpen,
  Paperclip,
  Plug,
  Plus,
  ReceiptText,
  RefreshCcw,
  RefreshCw,
  RotateCcw,
  Save,
  Search,
  Send,
  Settings,
  Settings2,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Star,
  Sun,
  Trash2,
  TriangleAlert,
  Upload,
  UploadCloud,
  UserPlus,
  UserRound,
  Users,
  UsersRound,
  X,
  XCircle,
} from "lucide-react"
export const iconsReference: { icon: LucideIcon; name: string; uses: number }[] = [
  { icon: AlertTriangle, name: "AlertTriangle", uses: 2 },
  { icon: AlignCenter, name: "AlignCenter", uses: 1 },
  { icon: AlignLeft, name: "AlignLeft", uses: 1 },
  { icon: AlignRight, name: "AlignRight", uses: 1 },
  { icon: AppWindow, name: "AppWindow", uses: 1 },
  { icon: ArrowDown, name: "ArrowDown", uses: 1 },
  { icon: ArrowDownRight, name: "ArrowDownRight", uses: 1 },
  { icon: ArrowLeft, name: "ArrowLeft", uses: 1 },
  { icon: ArrowRight, name: "ArrowRight", uses: 2 },
  { icon: ArrowUp, name: "ArrowUp", uses: 1 },
  { icon: ArrowUpDown, name: "ArrowUpDown", uses: 1 },
  { icon: ArrowUpRight, name: "ArrowUpRight", uses: 1 },
  { icon: BarChart3, name: "BarChart3", uses: 6 },
  { icon: Bell, name: "Bell", uses: 5 },
  { icon: BellRing, name: "BellRing", uses: 1 },
  { icon: Blocks, name: "Blocks", uses: 3 },
  { icon: BookOpen, name: "BookOpen", uses: 1 },
  { icon: Bot, name: "Bot", uses: 1 },
  { icon: Building2, name: "Building2", uses: 1 },
  { icon: CalendarDays, name: "CalendarDays", uses: 2 },
  { icon: CalendarPlus, name: "CalendarPlus", uses: 1 },
  { icon: ChartNoAxesCombined, name: "ChartNoAxesCombined", uses: 1 },
  { icon: Check, name: "Check", uses: 6 },
  { icon: CheckCheck, name: "CheckCheck", uses: 1 },
  { icon: CheckCircle2, name: "CheckCircle2", uses: 4 },
  { icon: ChevronDown, name: "ChevronDown", uses: 5 },
  { icon: ChevronLeft, name: "ChevronLeft", uses: 3 },
  { icon: ChevronRight, name: "ChevronRight", uses: 4 },
  { icon: CircleAlert, name: "CircleAlert", uses: 2 },
  { icon: CircleCheck, name: "CircleCheck", uses: 4 },
  { icon: CircleDollarSign, name: "CircleDollarSign", uses: 1 },
  { icon: CirclePause, name: "CirclePause", uses: 1 },
  { icon: Clock3, name: "Clock3", uses: 2 },
  { icon: Component, name: "Component", uses: 1 },
  { icon: Copy, name: "Copy", uses: 3 },
  { icon: CreditCard, name: "CreditCard", uses: 2 },
  { icon: Database, name: "Database", uses: 1 },
  { icon: Download, name: "Download", uses: 5 },
  { icon: ExternalLink, name: "ExternalLink", uses: 3 },
  { icon: File, name: "File", uses: 1 },
  { icon: FileChartColumn, name: "FileChartColumn", uses: 1 },
  { icon: FileText, name: "FileText", uses: 2 },
  { icon: FolderKanban, name: "FolderKanban", uses: 7 },
  { icon: FormInput, name: "FormInput", uses: 1 },
  { icon: Grid2X2, name: "Grid2X2", uses: 3 },
  { icon: GripVertical, name: "GripVertical", uses: 1 },
  { icon: HardDrive, name: "HardDrive", uses: 2 },
  { icon: Inbox, name: "Inbox", uses: 1 },
  { icon: Info, name: "Info", uses: 2 },
  { icon: KeyRound, name: "KeyRound", uses: 1 },
  { icon: Landmark, name: "Landmark", uses: 1 },
  { icon: Layers, name: "Layers", uses: 1 },
  { icon: LayoutDashboard, name: "LayoutDashboard", uses: 2 },
  { icon: LayoutPanelTop, name: "LayoutPanelTop", uses: 1 },
  { icon: List, name: "List", uses: 3 },
  { icon: ListFilter, name: "ListFilter", uses: 1 },
  { icon: LoaderCircle, name: "LoaderCircle", uses: 2 },
  { icon: LogIn, name: "LogIn", uses: 1 },
  { icon: Mail, name: "Mail", uses: 1 },
  { icon: Maximize2, name: "Maximize2", uses: 1 },
  { icon: Menu, name: "Menu", uses: 2 },
  { icon: MessageCircle, name: "MessageCircle", uses: 3 },
  { icon: Mic, name: "Mic", uses: 1 },
  { icon: Minus, name: "Minus", uses: 1 },
  { icon: Moon, name: "Moon", uses: 1 },
  { icon: MoreHorizontal, name: "MoreHorizontal", uses: 4 },
  { icon: MousePointerClick, name: "MousePointerClick", uses: 2 },
  { icon: PanelLeftClose, name: "PanelLeftClose", uses: 1 },
  { icon: PanelLeftOpen, name: "PanelLeftOpen", uses: 1 },
  { icon: Paperclip, name: "Paperclip", uses: 2 },
  { icon: Plug, name: "Plug", uses: 1 },
  { icon: Plus, name: "Plus", uses: 4 },
  { icon: ReceiptText, name: "ReceiptText", uses: 1 },
  { icon: RefreshCcw, name: "RefreshCcw", uses: 1 },
  { icon: RefreshCw, name: "RefreshCw", uses: 1 },
  { icon: RotateCcw, name: "RotateCcw", uses: 1 },
  { icon: Save, name: "Save", uses: 2 },
  { icon: Search, name: "Search", uses: 9 },
  { icon: Send, name: "Send", uses: 3 },
  { icon: Settings, name: "Settings", uses: 4 },
  { icon: Settings2, name: "Settings2", uses: 2 },
  { icon: ShieldCheck, name: "ShieldCheck", uses: 5 },
  { icon: ShoppingCart, name: "ShoppingCart", uses: 1 },
  { icon: SlidersHorizontal, name: "SlidersHorizontal", uses: 3 },
  { icon: Smartphone, name: "Smartphone", uses: 1 },
  { icon: Sparkles, name: "Sparkles", uses: 2 },
  { icon: Star, name: "Star", uses: 2 },
  { icon: Sun, name: "Sun", uses: 1 },
  { icon: Trash2, name: "Trash2", uses: 6 },
  { icon: TriangleAlert, name: "TriangleAlert", uses: 1 },
  { icon: Upload, name: "Upload", uses: 1 },
  { icon: UploadCloud, name: "UploadCloud", uses: 1 },
  { icon: UserPlus, name: "UserPlus", uses: 1 },
  { icon: UserRound, name: "UserRound", uses: 4 },
  { icon: Users, name: "Users", uses: 2 },
  { icon: UsersRound, name: "UsersRound", uses: 3 },
  { icon: X, name: "X", uses: 10 },
  { icon: XCircle, name: "XCircle", uses: 2 },
]
