"use client"

import { AreaChart, BarChart, DonutChart, HorizontalBarChart, LineChart, PieChart, Sparkline } from "@lexui/charts"
import { ArrowDownRight, ArrowUpRight, CircleDollarSign, Download, UsersRound } from "lucide-react"
import { Badge, Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Table, TableCell, TableContainer, TableHead, useToast } from "@lexui/react"

const data = [{ label: "Jan", value: 52 }, { label: "Fev", value: 61 }, { label: "Mar", value: 57 }, { label: "Abr", value: 78 }, { label: "Mai", value: 94 }, { label: "Jun", value: 88 }]
const segments = [{ label: "Enterprise", value: 48 }, { label: "Mid-market", value: 32 }, { label: "SMB", value: 20 }]
const channels = [{ label: "Orgânico", value: 84 }, { label: "Indicação", value: 67 }, { label: "Mídia", value: 52 }, { label: "Eventos", value: 31 }]
const tickets = [{ label: "Resolvidos", value: 148 }, { label: "Em andamento", value: 62 }, { label: "Aguardando", value: 38 }]

export default function DashboardPage() {
  const toast = useToast()
  const exportReport = () => { const blob = new Blob(["Mês,Receita\nJan,52\nFev,61\nMar,57\nAbr,78\nMai,94\nJun,88\n"], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "lexui-relatorio.csv"; link.click(); URL.revokeObjectURL(url); toast({ title: "Relatório exportado", description: "O arquivo CSV foi gerado no navegador.", variant: "success" }) }
  return <><header className="demo-page-header"><div><p className="demo-eyebrow">Visão geral</p><h1>Dashboard</h1><p>Acompanhe os principais indicadores da sua operação.</p></div><Button onClick={exportReport}><Download size={16} /> Exportar relatório</Button></header>
    <section className="demo-metric-grid" aria-label="Métricas"><Metric title="Receita" value="R$ 184.240" change="12,4%" positive icon={<CircleDollarSign />} sparkline={<Sparkline label="Tendência da receita" data={data} />} /><Metric title="Usuários ativos" value="8.429" change="8,1%" positive icon={<UsersRound />} sparkline={<Sparkline label="Tendência de usuários" data={[{ label: "Jan", value: 31 }, { label: "Fev", value: 42 }, { label: "Mar", value: 39 }, { label: "Abr", value: 54 }, { label: "Mai", value: 63 }]} />} /><Metric title="Cancelamentos" value="1,8%" change="0,4%" icon={<ArrowDownRight />} sparkline={<Sparkline label="Tendência de cancelamentos" tone="negative" data={[{ label: "Jan", value: 4 }, { label: "Fev", value: 5 }, { label: "Mar", value: 3 }, { label: "Abr", value: 3 }, { label: "Mai", value: 2 }]} />} /></section>
    <section className="demo-dashboard-grid"><Card className="demo-chart-card"><CardHeader><CardTitle>Receita recorrente</CardTitle><CardDescription>Últimos seis meses, em milhares de reais.</CardDescription></CardHeader><CardContent><BarChart data={data} label="Receita recorrente mensal" valueFormatter={(value) => `R$ ${value}k`} /></CardContent></Card><Card><CardHeader><CardTitle>Atividade recente</CardTitle><CardDescription>Eventos importantes da organização.</CardDescription></CardHeader><CardContent><div className="demo-activity"><Activity title="Novo usuário" detail="Marina Souza aceitou o convite" time="5 min" /><Activity title="Pagamento aprovado" detail="Fatura 2048" time="1 h" /><Activity title="Arquivo enviado" detail="relatorio-junho.pdf" time="3 h" /></div></CardContent></Card></section>
    <section className="demo-chart-gallery" aria-label="Galeria de gráficos">
      <Card><CardHeader><CardTitle>Crescimento da receita</CardTitle><CardDescription>Linha temporal para leitura de tendência.</CardDescription></CardHeader><CardContent><LineChart data={data} label="Crescimento mensal da receita" valueFormatter={(value) => `R$ ${value}k`} /></CardContent></Card>
      <Card><CardHeader><CardTitle>Volume de uso</CardTitle><CardDescription>Área acumulada de interações na plataforma.</CardDescription></CardHeader><CardContent><AreaChart data={[{ label: "Jan", value: 28 }, { label: "Fev", value: 44 }, { label: "Mar", value: 39 }, { label: "Abr", value: 62 }, { label: "Mai", value: 79 }, { label: "Jun", value: 96 }]} label="Volume mensal de uso" tone="positive" valueFormatter={(value) => `${value} mil`} /></CardContent></Card>
      <Card><CardHeader><CardTitle>Receita por segmento</CardTitle><CardDescription>Participação relativa por perfil de cliente.</CardDescription></CardHeader><CardContent><PieChart data={segments} label="Receita por segmento" valueFormatter={(value) => `${value}%`} /></CardContent></Card>
      <Card><CardHeader><CardTitle>Tickets por status</CardTitle><CardDescription>Distribuição atual da fila de suporte.</CardDescription></CardHeader><CardContent><DonutChart data={tickets} label="Tickets por status" centerValue="248" centerLabel="Tickets" /></CardContent></Card>
      <Card className="demo-chart-gallery__wide"><CardHeader><CardTitle>Aquisição por canal</CardTitle><CardDescription>Ranking de eficiência dos principais canais.</CardDescription></CardHeader><CardContent><HorizontalBarChart data={channels} label="Aquisição por canal" valueFormatter={(value) => `${value}%`} /></CardContent></Card>
    </section>
    <Card><CardHeader><CardTitle>Últimas transações</CardTitle><CardDescription>Movimentações processadas recentemente.</CardDescription></CardHeader><CardContent><TableContainer><Table><thead><tr><TableHead>Cliente</TableHead><TableHead>Data</TableHead><TableHead>Status</TableHead><TableHead>Valor</TableHead></tr></thead><tbody><tr><TableCell>Acme Ltda.</TableCell><TableCell>Hoje, 10:24</TableCell><TableCell><Badge variant="success">Pago</Badge></TableCell><TableCell>R$ 4.200,00</TableCell></tr><tr><TableCell>Orbital Studio</TableCell><TableCell>Ontem</TableCell><TableCell><Badge variant="warning">Pendente</Badge></TableCell><TableCell>R$ 1.850,00</TableCell></tr></tbody></Table></TableContainer></CardContent></Card>
  </>
}

function Metric({ title, value, change, positive, icon, sparkline }: { title: string; value: string; change: string; positive?: boolean; icon: React.ReactNode; sparkline: React.ReactNode }) { return <Card><CardHeader><div className="demo-metric__top"><CardDescription>{title}</CardDescription>{icon}</div><CardTitle className="demo-metric__value">{value}</CardTitle></CardHeader><CardContent><div><span className={positive ? "demo-positive" : "demo-negative"}>{positive ? <ArrowUpRight size={14} /> : <ArrowDownRight size={14} />}{change}</span><span className="demo-muted"> vs. mês anterior</span></div>{sparkline}</CardContent></Card> }
function Activity({ title, detail, time }: { title: string; detail: string; time: string }) { return <div className="demo-activity__item"><span className="demo-activity__dot" /><div><strong>{title}</strong><span>{detail}</span></div><time>{time}</time></div> }
